import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";

import {
  FileText,
  Download,
  RefreshCw,
  ShieldCheck,
  Network,
  AlertTriangle,
  Server,
  Clock,
  CheckCircle2,
  FileDown,
} from "lucide-react";

/* =========================================================
   DEMO REPORT DATA

   Temporary frontend data.
   Later this will come from FastAPI + Nmap.
========================================================= */

const reportData = {
  target: "10.59.47.15",
  scanType: "TCP + Service Detection",
  ports: 6,
  services: 6,
  findings: 6,
  highRisk: 3,
  mediumRisk: 2,
  review: 1,
  status: "Completed",
};

/* =========================================================
   FORMAT DATE
========================================================= */

function getCurrentDate() {
  return new Date().toLocaleString("en-IN", {
    dateStyle: "medium",
    timeStyle: "short",
  });
}

/* =========================================================
   REPORT CARD
========================================================= */

function ReportStat({ icon: Icon, label, value, iconColor }) {
  return (
    <motion.div
      whileHover={{
        y: -3,
      }}
      className="rounded-xl border border-white/5 bg-slate-950/40 p-4"
    >
      <div className="flex items-center justify-between">
        <p className="text-xs text-slate-500">
          {label}
        </p>

        <Icon
          size={17}
          className={iconColor}
        />
      </div>

      <p className="mt-2 text-xl font-bold text-white">
        {value}
      </p>
    </motion.div>
  );
}

/* =========================================================
   MAIN COMPONENT
========================================================= */

function Reports() {
  const [generatedAt, setGeneratedAt] =
    useState(getCurrentDate());

  const [isGenerating, setIsGenerating] =
    useState(false);

  const [generated, setGenerated] =
    useState(false);

  /* =======================================================
     GENERATE REPORT
  ======================================================= */

  const handleGenerateReport = () => {
    setIsGenerating(true);
    setGenerated(false);

    setTimeout(() => {
      setGeneratedAt(getCurrentDate());
      setIsGenerating(false);
      setGenerated(true);
    }, 1500);
  };

  /* =======================================================
     DOWNLOAD REPORT
  ======================================================= */

  const handleDownload = () => {
    const report = `
NETWORK PORT SCANNING & SECURITY ANALYSIS
==========================================

Target Information
------------------
Target IP: ${reportData.target}
Scan Type: ${reportData.scanType}
Scan Status: ${reportData.status}
Report Generated: ${generatedAt}

Scan Summary
------------
Open Ports: ${reportData.ports}
Services Detected: ${reportData.services}
Security Findings: ${reportData.findings}

Risk Summary
------------
High Priority: ${reportData.highRisk}
Medium Priority: ${reportData.mediumRisk}
Review Required: ${reportData.review}

Security Notes
--------------
This report summarizes observations from the network
security scan.

An open port or detected service does not by itself
confirm a vulnerability. Findings should be validated
and reviewed in the appropriate authorized environment.

Recommendations
---------------
1. Review unnecessary exposed services.
2. Restrict remote administration services.
3. Apply appropriate firewall rules.
4. Keep operating system and services updated.
5. Use secure protocols where appropriate.
6. Review SMB, RDP, FTP and other exposed services.
7. Re-scan after remediation.

Authorization
-------------
Only systems owned by the organization or systems for
which explicit permission has been provided should be
scanned.

==========================================
Generated by Network Security Analysis Platform
==========================================
`;

    const blob = new Blob([report], {
      type: "text/plain;charset=utf-8",
    });

    const url = URL.createObjectURL(blob);

    const link = document.createElement("a");

    link.href = url;

    link.download =
      `security-report-${reportData.target}.txt`;

    document.body.appendChild(link);

    link.click();

    document.body.removeChild(link);

    URL.revokeObjectURL(url);
  };

  return (
    <motion.section
      initial={{
        opacity: 0,
        y: 25,
      }}
      animate={{
        opacity: 1,
        y: 0,
      }}
      transition={{
        duration: 0.5,
        delay: 0.8,
      }}
      className="mt-6 rounded-2xl border border-white/10 bg-white/[0.03] p-6 backdrop-blur-xl"
    >
      {/* =================================================
          HEADER
      ================================================== */}

      <div className="flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between">
        <div className="flex items-center gap-3">
          <div className="rounded-xl bg-purple-500/10 p-3 text-purple-400">
            <FileText size={21} />
          </div>

          <div>
            <h2 className="font-semibold text-white">
              Security Reports
            </h2>

            <p className="mt-1 text-xs text-slate-500">
              Generate and review security scan reports
            </p>
          </div>
        </div>

        {/* Generate Button */}

        <motion.button
          type="button"
          onClick={handleGenerateReport}
          disabled={isGenerating}
          whileHover={
            !isGenerating
              ? {
                  scale: 1.02,
                }
              : {}
          }
          whileTap={
            !isGenerating
              ? {
                  scale: 0.97,
                }
              : {}
          }
          className="flex items-center justify-center gap-2 rounded-xl bg-purple-600 px-5 py-3 text-sm font-semibold text-white shadow-lg shadow-purple-600/20 transition hover:bg-purple-500 disabled:cursor-not-allowed disabled:bg-slate-700 disabled:shadow-none"
        >
          <RefreshCw
            size={17}
            className={
              isGenerating
                ? "animate-spin"
                : ""
            }
          />

          {isGenerating
            ? "GENERATING..."
            : "GENERATE REPORT"}
        </motion.button>
      </div>

      {/* =================================================
          SUCCESS MESSAGE
      ================================================== */}

      <AnimatePresence>
        {generated && (
          <motion.div
            initial={{
              opacity: 0,
              y: -8,
            }}
            animate={{
              opacity: 1,
              y: 0,
            }}
            exit={{
              opacity: 0,
              y: -8,
            }}
            className="mt-5 flex items-center gap-2 rounded-xl border border-emerald-500/10 bg-emerald-500/[0.04] px-4 py-3 text-sm text-emerald-400"
          >
            <CheckCircle2 size={17} />

            Report generated successfully.
          </motion.div>
        )}
      </AnimatePresence>

      {/* =================================================
          REPORT PREVIEW
      ================================================== */}

      <div className="mt-6 overflow-hidden rounded-2xl border border-white/10 bg-slate-950/40">
        {/* Report Header */}

        <div className="border-b border-white/10 p-6">
          <div className="flex flex-col gap-5 md:flex-row md:items-center md:justify-between">
            <div className="flex items-start gap-4">
              <div className="rounded-xl bg-white/5 p-3 text-slate-300">
                <FileText size={22} />
              </div>

              <div>
                <h3 className="text-base font-semibold text-white">
                  Network Security Analysis Report
                </h3>

                <p className="mt-1 text-xs text-slate-500">
                  Security assessment summary
                </p>
              </div>
            </div>

            <div className="flex items-center gap-2">
              <span className="flex items-center gap-1.5 rounded-full border border-emerald-500/20 bg-emerald-500/10 px-3 py-1.5 text-[10px] font-semibold text-emerald-400">
                <span className="h-1.5 w-1.5 rounded-full bg-emerald-400" />
                COMPLETED
              </span>
            </div>
          </div>
        </div>

        {/* =================================================
            REPORT METADATA
        ================================================== */}

        <div className="grid gap-4 border-b border-white/10 p-6 sm:grid-cols-2 lg:grid-cols-4">
          <div>
            <p className="text-[10px] uppercase tracking-wider text-slate-600">
              Target
            </p>

            <p className="mt-2 font-mono text-sm text-blue-400">
              {reportData.target}
            </p>
          </div>

          <div>
            <p className="text-[10px] uppercase tracking-wider text-slate-600">
              Scan Type
            </p>

            <p className="mt-2 text-sm text-slate-300">
              {reportData.scanType}
            </p>
          </div>

          <div>
            <p className="text-[10px] uppercase tracking-wider text-slate-600">
              Generated
            </p>

            <p className="mt-2 flex items-center gap-1.5 text-sm text-slate-300">
              <Clock size={14} />
              {generatedAt}
            </p>
          </div>

          <div>
            <p className="text-[10px] uppercase tracking-wider text-slate-600">
              Status
            </p>

            <p className="mt-2 flex items-center gap-1.5 text-sm text-emerald-400">
              <ShieldCheck size={14} />
              {reportData.status}
            </p>
          </div>
        </div>

        {/* =================================================
            REPORT STATS
        ================================================== */}

        <div className="grid gap-4 p-6 sm:grid-cols-2 lg:grid-cols-4">
          <ReportStat
            icon={Network}
            label="Open Ports"
            value={reportData.ports}
            iconColor="text-blue-400"
          />

          <ReportStat
            icon={Server}
            label="Services"
            value={reportData.services}
            iconColor="text-purple-400"
          />

          <ReportStat
            icon={AlertTriangle}
            label="Findings"
            value={reportData.findings}
            iconColor="text-orange-400"
          />

          <ReportStat
            icon={ShieldCheck}
            label="Risk Score"
            value="62/100"
            iconColor="text-emerald-400"
          />
        </div>

        {/* =================================================
            RISK SUMMARY
        ================================================== */}

        <div className="px-6 pb-6">
          <div className="rounded-xl border border-white/5 bg-white/[0.02] p-5">
            <div className="mb-4 flex items-center justify-between">
              <div>
                <h3 className="text-sm font-semibold text-white">
                  Risk Summary
                </h3>

                <p className="mt-1 text-xs text-slate-600">
                  Findings requiring security review
                </p>
              </div>
            </div>

            <div className="grid gap-3 sm:grid-cols-3">
              <div className="rounded-xl border border-red-500/10 bg-red-500/[0.03] p-4">
                <p className="text-xs text-red-400">
                  High Priority
                </p>

                <p className="mt-1 text-xl font-bold text-white">
                  {reportData.highRisk}
                </p>
              </div>

              <div className="rounded-xl border border-orange-500/10 bg-orange-500/[0.03] p-4">
                <p className="text-xs text-orange-400">
                  Medium Priority
                </p>

                <p className="mt-1 text-xl font-bold text-white">
                  {reportData.mediumRisk}
                </p>
              </div>

              <div className="rounded-xl border border-blue-500/10 bg-blue-500/[0.03] p-4">
                <p className="text-xs text-blue-400">
                  Review Required
                </p>

                <p className="mt-1 text-xl font-bold text-white">
                  {reportData.review}
                </p>
              </div>
            </div>
          </div>
        </div>

        {/* =================================================
            DOWNLOAD
        ================================================== */}

        <div className="flex flex-col gap-4 border-t border-white/10 bg-white/[0.01] p-6 sm:flex-row sm:items-center sm:justify-between">
          <div className="flex items-center gap-3">
            <FileDown
              size={19}
              className="text-slate-500"
            />

            <div>
              <p className="text-sm font-medium text-slate-300">
                Export Security Report
              </p>

              <p className="mt-1 text-xs text-slate-600">
                Download the current report summary
              </p>
            </div>
          </div>

          <button
            type="button"
            onClick={handleDownload}
            className="flex items-center justify-center gap-2 rounded-xl border border-white/10 px-5 py-2.5 text-xs font-semibold text-slate-300 transition hover:border-blue-500/20 hover:bg-blue-500/10 hover:text-blue-400"
          >
            <Download size={16} />
            DOWNLOAD REPORT
          </button>
        </div>
      </div>

      {/* =================================================
          SECURITY NOTICE
      ================================================== */}

      <div className="mt-5 flex items-start gap-3 rounded-xl border border-blue-500/10 bg-blue-500/[0.03] p-4">
        <ShieldCheck
          size={17}
          className="mt-0.5 shrink-0 text-blue-400"
        />

        <p className="text-xs leading-relaxed text-slate-500">
          Reports summarize observed network services and
          security review priorities. An observed open port
          does not by itself confirm a vulnerability.
        </p>
      </div>
    </motion.section>
  );
}

export default Reports;